apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  labels:
    type: cache
spec:
  template:
    metadata:
      labels:
        type: cache
    spec:
      containers:
      - name: redis
        image: redis
  replicas: 3